/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nicovilab.profeconecta.view;

import com.nicovilab.profeconecta.view.extraSwingComponents.TextPrompt;

import java.awt.*;
import javax.swing.border.LineBorder;

import com.nicovilab.profeconecta.view.gradientComponents.ButtonGradient;
import com.nicovilab.profeconecta.view.gradientComponents.JPanelGradient;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import lombok.Getter;
/**
 *
 * @author Nico
 */
@Getter
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setupCardLayout();
        pack();
        setVisible(true);
        setLocationRelativeTo(null); // Centrar la ventana

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

    }// </editor-fold>//GEN-END:initComponents

    private CardLayout cardLayout;
    private JPanel contentPanel;
    
    
    //Declarar variables de los paneles de las vistas
    public SignUpPanel signUpPanel;
    public LoginPanel loginPanel;
    public UserPanel userPanel;
    public ProfilePanel profilePanel;
    
     private void setupCardLayout() {
        // 1. Crear el panel contenedor con CardLayout
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);

        signUpPanel = new SignUpPanel(this);
        loginPanel = new LoginPanel(this);
        userPanel = new UserPanel(this);
        profilePanel = new ProfilePanel(this);
        
        contentPanel.add(loginPanel, "login");
        contentPanel.add(signUpPanel, "signup");
        contentPanel.add(userPanel, "userpanel");
        contentPanel.add(profilePanel, "profile");

        
        setContentPane(contentPanel);
        
        cardLayout.show(contentPanel, "login");
        
        pack();
    }
    
    // Método para cambiar entre paneles
    public void showPanel(String panelName) {
        cardLayout.show(contentPanel, panelName);
    }

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
