/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.nicovilab.profeconecta.view;

import com.github.lgooddatepicker.components.CalendarPanel;
import com.github.lgooddatepicker.components.DatePickerSettings;
import com.nicovilab.profeconecta.view.BookingHighlightPolicy.BookingHighlightPolicy;
import com.nicovilab.profeconecta.view.gradientComponents.CircularIntegratedButton;
import com.nicovilab.profeconecta.view.gradientComponents.JPanelGradient;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.Set;
import javax.swing.Timer;
import lombok.Data;

/**
 *
 * @author Nico
 */
@Data
public class UserAdDetailDialog extends javax.swing.JDialog {

    /**
     * Creates new form UserAdDetailDialog
     */
    public UserAdDetailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightPanel = new JPanelGradient(new Color(230, 243, 250), new Color(255,255,255));
        imageAvatar = new com.nicovilab.profeconecta.view.extraSwingComponents.ImageAvatar();
        nameTextField = new javax.swing.JTextField();
        surnameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        townLabel = new javax.swing.JLabel();
        provinceLabel = new javax.swing.JLabel();
        mainSeparator = new javax.swing.JSeparator();
        opinionLabel = new javax.swing.JLabel();
        reviewsScrollPane = new javax.swing.JScrollPane();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        star6 = new javax.swing.JLabel();
        star7 = new javax.swing.JLabel();
        star8 = new javax.swing.JLabel();
        star9 = new javax.swing.JLabel();
        star10 = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        provinceTextField = new javax.swing.JTextField();
        townTextField = new javax.swing.JTextField();
        rateUserButton = new javax.swing.JButton();
        calendarPanel = new com.github.lgooddatepicker.components.CalendarPanel();
        bookingButton = new javax.swing.JButton();
        informationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rightPanel.setBackground(new java.awt.Color(235, 235, 235));
        rightPanel.setPreferredSize(new java.awt.Dimension(600, 0));

        imageAvatar.setBackground(new java.awt.Color(255, 255, 255));
        imageAvatar.setForeground(new java.awt.Color(255, 51, 0));
        imageAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultAvatar.png"))); // NOI18N

        nameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTextField.setToolTipText("");
        nameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 117, 191), 2));
        nameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTextField.setMaximumSize(new java.awt.Dimension(60, 30));
        nameTextField.setPreferredSize(new java.awt.Dimension(60, 30));
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
        });
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        surnameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameTextField.setToolTipText("");
        surnameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 117, 191), 2));
        surnameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        surnameTextField.setMaximumSize(new java.awt.Dimension(60, 30));
        surnameTextField.setPreferredSize(new java.awt.Dimension(60, 30));
        surnameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                surnameTextFieldFocusGained(evt);
            }
        });
        surnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextFieldActionPerformed(evt);
            }
        });

        nameLabel.setText("Nombre");
        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        surnameLabel.setText("Apellidos");
        surnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        townLabel.setText("Municipio");
        townLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        provinceLabel.setText("Provincia");
        provinceLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        opinionLabel.setText("Opiniones");
        opinionLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        reviewsScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 117, 191)));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 117, 191)));
        descriptionScrollPane.setViewportView(descriptionTextArea);

        descriptionLabel.setText("Descripción");
        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf1.png"))); // NOI18N

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf2.png"))); // NOI18N
        star2.setIconTextGap(0);

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf1.png"))); // NOI18N

        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf2.png"))); // NOI18N
        star4.setIconTextGap(0);

        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf1.png"))); // NOI18N

        star6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf2.png"))); // NOI18N
        star6.setIconTextGap(0);

        star7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf1.png"))); // NOI18N

        star8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf2.png"))); // NOI18N
        star8.setIconTextGap(0);

        star9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf1.png"))); // NOI18N

        star10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starHalf2.png"))); // NOI18N
        star10.setIconTextGap(0);

        ratingLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        provinceTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        provinceTextField.setToolTipText("");
        provinceTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 117, 191), 2));
        provinceTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        provinceTextField.setMaximumSize(new java.awt.Dimension(60, 30));
        provinceTextField.setPreferredSize(new java.awt.Dimension(60, 30));
        provinceTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                provinceTextFieldFocusGained(evt);
            }
        });
        provinceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceTextFieldActionPerformed(evt);
            }
        });

        townTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        townTextField.setToolTipText("");
        townTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 117, 191), 2));
        townTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        townTextField.setMaximumSize(new java.awt.Dimension(60, 30));
        townTextField.setPreferredSize(new java.awt.Dimension(60, 30));
        townTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                townTextFieldFocusGained(evt);
            }
        });
        townTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townTextFieldActionPerformed(evt);
            }
        });

        rateUserButton.setText("Valorar");

        bookingButton.setText("Reservar");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        informationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightPanelLayout.createSequentialGroup()
                                .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameLabel)
                                            .addComponent(provinceLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(townLabel)
                                            .addComponent(surnameLabel)
                                            .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(provinceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(townTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(rightPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descriptionLabel)
                                    .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(bookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightPanelLayout.createSequentialGroup()
                                .addComponent(opinionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(star1)
                                .addGap(0, 0, 0)
                                .addComponent(star2)
                                .addGap(0, 0, 0)
                                .addComponent(star3)
                                .addGap(0, 0, 0)
                                .addComponent(star4)
                                .addGap(0, 0, 0)
                                .addComponent(star5)
                                .addGap(0, 0, 0)
                                .addComponent(star6)
                                .addGap(0, 0, 0)
                                .addComponent(star7)
                                .addGap(0, 0, 0)
                                .addComponent(star8)
                                .addGap(0, 0, 0)
                                .addComponent(star9)
                                .addGap(0, 0, 0)
                                .addComponent(star10)
                                .addGap(18, 18, 18)
                                .addComponent(ratingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rateUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mainSeparator)
                            .addComponent(reviewsScrollPane)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(informationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(surnameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provinceLabel)
                            .addComponent(townLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provinceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(townTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bookingButton)
                        .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(star5)
                    .addComponent(star6)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(opinionLabel)
                                .addComponent(star1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(star2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(star3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(star4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(star7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(star8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(star9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(star10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ratingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rateUserButton))
                        .addGap(1, 1, 1)
                        .addComponent(reviewsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained

    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void surnameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTextFieldFocusGained

    private void surnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTextFieldActionPerformed

    private void provinceTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_provinceTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_provinceTextFieldFocusGained

    private void provinceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinceTextFieldActionPerformed

    private void townTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_townTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_townTextFieldFocusGained

    private void townTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_townTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_townTextFieldActionPerformed

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingButtonActionPerformed

    public CalendarPanel getCalendarPanel() {
        return this.calendarPanel;
    }

    public void addRateUserButtonActionListener(ActionListener al) {
        this.rateUserButton.addActionListener(al);
    }

    public void setNameTextField(String text) {
        this.nameTextField.setText(text);
    }

    public void setSurnameTextField(String text) {
        this.surnameTextField.setText(text);
    }

    public void setProvinceTextField(String text) {
        this.provinceTextField.setText(text);
    }

    public void setTownTextField(String text) {
        this.townTextField.setText(text);
    }

    public void setDescriptionTextField(String text) {
        this.descriptionTextArea.setText(text);
    }

    public void enableFields(boolean enable) {
        this.nameTextField.setEnabled(enable);
        this.surnameTextField.setEnabled(enable);
        this.provinceTextField.setEnabled(enable);
        this.townTextField.setEnabled(enable);
        this.descriptionTextArea.setEnabled(enable);
    }

    public void updateCalendarHighlighting(Set<LocalDate> noBookingDates, Set<LocalDate> availableBookingDates, Set<LocalDate> fullyBookedDates) {
        DatePickerSettings settings = new DatePickerSettings();
        settings.setHighlightPolicy(new BookingHighlightPolicy(noBookingDates, availableBookingDates, fullyBookedDates));
        getCalendarPanel().setSettings(settings);
    }

    public void addBookingButtonActionListener(ActionListener al) {
        this.bookingButton.addActionListener(al);
    }

    public void setInformationTextField(String text, Color color) {
        this.informationLabel.setText(text);
        this.informationLabel.setForeground(color);

        Timer t = new Timer(2500, (ActionEvent e) -> {
            informationLabel.setText("");
            informationLabel.setForeground(Color.black);
        });
        t.setRepeats(false);
        t.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingButton;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private com.nicovilab.profeconecta.view.extraSwingComponents.ImageAvatar imageAvatar;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JSeparator mainSeparator;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel opinionLabel;
    private javax.swing.JLabel provinceLabel;
    private javax.swing.JTextField provinceTextField;
    private javax.swing.JButton rateUserButton;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JScrollPane reviewsScrollPane;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star10;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    private javax.swing.JLabel star6;
    private javax.swing.JLabel star7;
    private javax.swing.JLabel star8;
    private javax.swing.JLabel star9;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JLabel townLabel;
    private javax.swing.JTextField townTextField;
    // End of variables declaration//GEN-END:variables
}
